spring:
  application:
    name: java-cloudinary
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI}
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  folder: ${CLOUDINARY_FOLDER}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}